# Generated by Django 5.1.3 on 2025-12-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_experience"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="tech_stack",
        ),
        migrations.AddField(
            model_name="project",
            name="architecture",
            field=models.CharField(
                blank=True, help_text="Ex: MVC, REST API, Microservices", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="backend",
            field=models.CharField(
                blank=True, help_text="Ex: Django, FastAPI, Laravel", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="database",
            field=models.CharField(
                blank=True, help_text="Ex: PostgreSQL, MySQL, MongoDB", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="frontend",
            field=models.CharField(
                blank=True, help_text="Ex: HTML5, CSS3, JavaScript", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="security",
            field=models.CharField(
                blank=True, help_text="Ex: JWT, bcrypt, CSRF protection", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="tools",
            field=models.CharField(
                blank=True, help_text="Ex: Git, Docker, GitHub Actions", max_length=200
            ),
        ),
    ]
