# Generated by Django 5.0.1 on 2025-12-30 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_remove_project_tech_stack_project_architecture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.URLField(help_text="URL to project image"),
        ),
        migrations.AlterField(
            model_name="skill",
            name="icon",
            field=models.URLField(blank=True, help_text="URL to icon image", null=True),
        ),
    ]
